<?php
/**
 *  HTML Invoice

 *	This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  @category   PAJ
 *  @package    HTMLInvoice
 *  @license    http://www.gnu.org/licenses/ GNU General Public License
 * 
 *
 */

if(isset($_GET['orderid'])){ $_orderID = $_GET['orderid'];} else { $_orderID = false;}	
if(isset($_GET['addvat'])){ $_addVAT = 'TRUE';} else { $_addVAT = 'FALSE';}
if(isset($_GET['print'])){ $_print= 'TRUE';} else { $_print = 'FALSE';};

$_orderIDs=explode('|',$_orderID);

$_invoiceCount=count($_orderIDs);

?>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Invoice</title>
<style type="text/css">
BODY {
	font-family: Arial, Helvetica, sans-serif;
	margin: 0;
	padding: 0;
	font-size: 12px;
}
.wrapper {
	margin: 20px;
}
.dataTableHeadingRow {
	background: none;
}
.dataTableHeadingContent {
	font-size: 12px;
	color: #000;
	padding: 6px;
	border-bottom: 2px solid #999;
}
.dataTableRow {
	background: none;
}
.dataTableContent {
	padding: 2px 6px;
	border-bottom: 1px solid #eee;
}

.alt TD { background: #eee; }

.page-break	{ display: none; }

@media screen {
	#printFooter {
		display: none;
	}
}
@media print {
	#printFooter {
		position: fixed;
		bottom: 0;
	}
	
	.page-break	{ display: block; page-break-before: always; }
}

#footer {
	text-align: center;
	margin: 60px 0 0 0;
	color: #666;
}
#notes {
	border: 1px solid #999;
	width: 530px;
	height: 80px;
	padding: 5px;
	margin: 0 0 0 20px;
}
#notes TEXTAREA {
	border: none;
	width: 470px;
	height: 60px;
	overflow: hidden;
	margin: 5px 0 0 0;
	border: 0;
}
a.addr_link {
	color: #000;
	text-decoration: none;
}
.option-menu {
	padding: 8px;
	background: #eee;
	font-size: 10px;
}
.totals .label {
	padding: 5px 20px 5px 0;
}
.totals .total td {
	font-size: 1.3em;
	border-top: 1px solid #ccc;
}
div.watermark {
	display:block;
	position:fixed;
	z-index:100;
	width:100%;
	height:100%;
}
 div.content > *:first-child, x:-moz-any-link {
margin-top:0;
}/* ff only */
 div.watermark, x:-moz-any-link {
z-index:auto;
}/* ff only */
 div.watermark, x:-moz-any-link, x:default {
z-index:100;
}/* ff3 only */
 @media all and (min-width: 0px) {
div.watermark {
width:8.5in;
}
} /* opera only */
div.watermark div {
	position:absolute;
	left:0;
	width:99%;
}
/* watermark position */
/* horizontal */
div.left {
	text-align:left;
}
div.center {
	text-align:center;
}
div.right {
	text-align:right;
}
 body:last-child:not(:root:root) div.right div {
left:-160px;
}/* safari only */
/* vertical */
div.top div {
	top:0;
}
div.middle div {
	top:50%;
	margin-top:-210px;
}
div.bottom div {
	bottom:2px;
}
.clearfix:after {
	content: ".";
	display: block;
	height: 0;
	clear: both;
	visibility: hidden;
}
.clearfix {
	display: inline-block;
}  /* for IE/Mac */


.button {
	-moz-box-shadow:inset 0px 1px 0px 0px #fce2c1;
	-webkit-box-shadow:inset 0px 1px 0px 0px #fce2c1;
	box-shadow:inset 0px 1px 0px 0px #fce2c1;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ffc477), color-stop(1, #fb9e25) );
	background:-moz-linear-gradient( center top, #ffc477 5%, #fb9e25 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffc477', endColorstr='#fb9e25');
	background-color:#ffc477;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #eeb44f;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #cc9f52;
}.button:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #fb9e25), color-stop(1, #ffc477) );
	background:-moz-linear-gradient( center top, #fb9e25 5%, #ffc477 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fb9e25', endColorstr='#ffc477');
	background-color:#fb9e25;
}.button:active {
	position:relative;
	top:1px;
}
</style>
<style media="print" type="text/css">
.wrapper {
	margin: 0;
}
.option-menu {
	display: none;
}
</style>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
<script>
jQuery(document).ready(function(){
	
	var invoiceCount=<?php echo $_invoiceCount ?>;
	var orderids="<?php echo $_orderID ?>";
	var orderid=orderids.split("|");
	
	for (var i=1;i<=invoiceCount;i++)
	{ 
		//alert (orderid[i-1]);
		if (orderid[i-1] != '') {
			getInvoice(orderid[i-1],i);
		}
	}
	
	
	<?php if ($_print=='TRUE'): ?>
	window.print();
	<?php endif; ?>

	function getInvoice(orderid,index)
	{
		error(0);

		var data = [];
		data.push ({ name: "variables", value: "true" });
		data.push ({ name: "orderid", value: orderid });
		data.push ({ name: "addvat", value: '<?php echo $_addVAT ?>' });
		data.push ({ name: "storeid", value: '0' });
		data.push ({ name: "print", value: '<?php echo $_print ?>' });
		
			
		$.ajax({
			type: "POST",
			timeout:8000,
			cache: false,
			async: false,
			url: "../index.php?ajax=true&class=MagentoInvoice",
			data: data,
			dataType: "json",
			success: function(php){
				
				if(php.status==='success')
				{
					$('#loading_' + index).remove();
					
					$('#pageheader').html(php.pageheader);
					$('#invoiceheader_' + index).append(php.invoiceheader);
					$('#invoiceheadertable_' + index).append(php.invoiceheadertable);
					$('#invoiceitemstable_' + index).append(php.invoiceitemstable);
					$('#invoicefooter_' + index).append(php.invoicefooter);
					
						$("#cbk_paid").click(function(){
							if (index < 2) {
								$("#watermark_graphic").toggle(); 
							} else {
								alert ('Watermark valid for single order view only.');
							}								
						});
				
				} else {
					error(1,php.errormessage);
				}
				
			},
			error: function(jqXHR, textStatus, errorThrown){
			
				if(errorThrown==='timeout') {
					
					error(1,'Request timed out, please try again.');

				} else if (textStatus==='parsererror') {
					
					error(1,'An error occured trying to complete this request - '+ textStatus);

				} else {
					
					error(1,textStatus);
				}
				
				hideshow('loading',0,0);
			}
			
		});	
	}	
	
	function error(act,txt)
	{
		hideshow('error',act);
		if(txt) $('#error').html(txt);
	}
	
	function hideshow(el,act,fade)
	{
		if (typeof fade === "undefined" || fade===null) fade = 1;
		
		if(act) {
			$('#'+el).css('visibility','visible');
			if(fade) {
				setTimeout(function() {
					$('#'+el).fadeOut("slow", function() {
						$('#'+el).show().css({visibility: "hidden"});
					});
				}, 10000);
			}
		} else {
			$('#'+el).css('visibility','hidden');
		}
	}
	

	// function to fade out an elephant
	//
	function elFadeOut(el)
	{
	   setTimeout(function() {
			$(el).css('visibility','visible');
				$(el).fadeOut("slow", function() {
					$(el).show().css({visibility: "hidden"});
				});
			
		}, 8000);	
	}


});
</script>
</head>
<body>
<div style="display: none;" id="error">&nbsp;</div>
<div id="pageheader"></div>
<?php for($i = 1;$i <= $_invoiceCount;$i++) : ?>
<div id="invoice_<?php echo ($i) ?>" class="wrapper">
	<div id="loading_<?php echo ($i) ?>"><img alt="Loading..." src="images/ajax-loader.gif" width="200"></div>
	<div id="invoiceheader_<?php echo ($i) ?>"></div>	
	<div id="invoiceheadertable_<?php echo ($i) ?>"></div>	
	<div id="invoiceitemstable_<?php echo ($i) ?>"></div>
	<div id="invoicefooter_<?php echo ($i) ?>"></div>
</div>
<div class="page-break"></div>
<?php endfor; ?>
</body>
</html>
